sh_yaw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sh_yaw_joint
    joint_speed: 2.0
    motor:
        id: 21
        init: 512
        min: 0
        max: 1023

sh_pitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sh_pitch_joint
    joint_speed: 2.0
    motor:
        id: 22
        init: 512
        min: 0
        max: 1023
